<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.17"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>xvsdk: Main Page</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">xvsdk
   &#160;<span id="projectnumber">3.2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.17 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="PageDoc"><div class="header">
  <div class="headertitle">
<div class="title">xvsdk Documentation</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><h1>!! Draft version !!</h1>
<h2><a href="./annotated.html">C++ API Reference</a></h2>
<h2>Some conventions</h2>
<ul>
<li><b>physical units</b> are all in SI (International System of Units) by default (second, meter, radian ..), otherwise the name is suffixed with unit (example: <code>interEyesDistanceMm</code> if is in mm or <code>edgeTimestampUs</code> if timestamp in microseconds).</li>
<li><b>3D rotation:</b> we use right handed convention, recommand to use rotation matrix as many as possible or quaternions if need less memory usage. SDK provides tools for conversions between 3D rotation formats (see <a class="el" href="group__xv__rotation__conversions.html">functions to convert between 3D rotations representations</a>) and other conventions (left handed).</li>
<li><b>device frame coordinates</b> is based on the IMU frame coordinates with X to right, Y to down and Z to forward (main direction of the cameras).</li>
<li><b>world frame coordinates</b> is usually aligned with gravity (using the IMU) and X to right, Y to down and Z to forward of the initial pose.</li>
<li><b>components frame coordinates</b> (stereo cameras, ToF, color camera, AR/VR displays ...) are usually defined by calibration and are defined according to the device frame coordianates (IMU)</li>
<li><b>timestamps:</b> the API usually use the two following timestamps fields:<ul>
<li><code>double hostTimestamp</code> : host timestamp in seconds of the physical event of the data based on <code>std::chrono::steady_clock</code> that is guaranteed to be monotonic by the C++ STL</li>
<li><code>std::int64_t edgeTimestampUs</code> : timestamp of the physical event of the data based on edge clock</li>
</ul>
</li>
</ul>
<h2>Examples</h2>
<p>The main entry point to use a XVisio is <a class="el" href="classxv_1_1Device.html">xv::Device</a>. This class is the main entry point of the API, it gives access to the device and algorithms. See <a class="el" href="group__xv__functions.html#ga7a7e38fd3ed94aab311fbc1ce5bd7693" title="Retrieve all the detected XVisio devices. If no device is found after the timeout is reached,...">xv::getDevices()</a> to have an instance corresponding to a device.</p>
<p>A device can have multiple components, accessible with member functions :</p><ul>
<li><a class="el" href="classxv_1_1Device.html#a82af73bff459756055b16f4919621472" title="Get the SLAM component.">xv::Device::slam()</a> : 6dof tracker doing the SLAM algorithm on host based on informations coming from device (stereo camera, IMU sensor, ..)</li>
<li><a class="el" href="classxv_1_1Device.html#aab6d916babd2f4f78d5f12c00847394f" title="Get the IMU sensor of the device.">xv::Device::imuSensor()</a> : sensor with at least 3-axis accelerometer and 3-axis gyrometer</li>
<li><a class="el" href="classxv_1_1Device.html#a160863c661624997a5db4ffe20306bd8" title="Get the stereo cameras component of the device.">xv::Device::fisheyeCameras()</a>: typically 2 fisheye cameras used for Visual SLAM</li>
<li><a class="el" href="classxv_1_1Device.html#aeab96f3c3a38b0771126a4fd9b1d7fe0" title="Get the ToF component of the device.">xv::Device::tofCamera()</a>: a depth camera sensor</li>
<li>#xv::Device::edge(): used to run some algorithm directly on embedded device (typically Visual SLAM) when it is possible to choose between host and edge processing</li>
<li><a class="el" href="classxv_1_1Device.html#a088d0774607e803076cb889e70af2036" title="Get the display component.">xv::Device::display()</a>: used to handle informations about the display (if device can display like a HMD)</li>
<li><a class="el" href="classxv_1_1Device.html#a16049ac3cef9f3035e45675a63dfaa8d" title="Get the object detection component.">xv::Device::objectDetector()</a>: used to run and get results of the CNN object detector</li>
</ul>
<p>If a device does not support a component or doesn't have the component (for example ToF), the accessor function will return <code>null_ptr</code>. The data streams and processings under a component are activated only if at least one callback is registerd to the component. If all the callbacks are unregistered then steams can be deactivated.</p>
<p>Here are some example how to use the differents components.</p>
<h3>6dof tracking with SLAM on host and get fisheye images</h3>
<div class="fragment"><div class="line"><span class="preprocessor">#include &lt;xv-sdk.h&gt;</span></div>
<div class="line"> </div>
<div class="line"><span class="preprocessor">#include &lt;iostream&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;thread&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;atomic&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;cmath&gt;</span></div>
<div class="line"> </div>
<div class="line"><span class="preprocessor">#include &quot;frequency_counter.hpp&quot;</span></div>
<div class="line"> </div>
<div class="line"><span class="keywordtype">void</span> onPose(<a class="code" href="structxv_1_1Pose.html">xv::Pose</a> <span class="keyword">const</span>&amp; pose){</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// use the conversion function to get the pitch, yaw and roll of the orientation</span></div>
<div class="line">    <span class="comment">// (be carefull of gimbal lock of Euler angles, that is why Euler angles are not in Pose structure)</span></div>
<div class="line">    <span class="keyword">auto</span> pitchYawRoll = <a class="code" href="group__xv__rotation__conversions.html#ga2e933d4631944d4ab6ff3d0aa0ce7223">xv::rotationToPitchYawRoll</a>(pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#ade74f0f888c9c3727e737114d39689f4">rotation</a>());</div>
<div class="line">    <span class="keyword">static</span> FrequencyCounter fps;</div>
<div class="line">    fps.tic();</div>
<div class="line">    <span class="keywordflow">if</span> (fps.count() % 500 == 1) {</div>
<div class="line">        std::cout &lt;&lt; <span class="stringliteral">&quot;SLAM pose callback : &quot;</span> &lt;&lt; fps.fps() &lt;&lt; <span class="stringliteral">&quot; Hz [timestamp=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1PoseRot__.html#a8013d9baf7f36cb63d15070ab1b92db0">hostTimestamp</a>() &lt;&lt; <span class="stringliteral">&quot; x=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a5d341d3f04038517496720505a27d492">x</a>() &lt;&lt; <span class="stringliteral">&quot; y=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a8c459545f7d46d2f237628fce8c05b2f">y</a>() &lt;&lt; <span class="stringliteral">&quot; z=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a28695437773c81547650749af7abd45f">z</a>()</div>
<div class="line">                  &lt;&lt; <span class="stringliteral">&quot; pitch=&quot;</span>  &lt;&lt; pitchYawRoll[0]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; yaw=&quot;</span>  &lt;&lt; pitchYawRoll[1]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; roll=&quot;</span>  &lt;&lt; pitchYawRoll[2]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span></div>
<div class="line">                  &lt;&lt; std::endl;</div>
<div class="line">    }</div>
<div class="line">}</div>
<div class="line"> </div>
<div class="line">std::shared_ptr&lt;const xv::FisheyeImages&gt; lastStereoImage;</div>
<div class="line"> </div>
<div class="line"><span class="keywordtype">int</span> main( <span class="keywordtype">int</span> <span class="comment">/*argc*/</span>, <span class="keywordtype">char</span>* <span class="comment">/*argv*/</span>[] )</div>
<div class="line">{</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// may change the log level this way :</span></div>
<div class="line">    <a class="code" href="group__xv__functions.html#ga32fe1b6690843af286b55a88691c10fa">xv::setLogLevel</a>(xv::LogLevel::debug);</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// return a map of devices with serial number as key, wait at most 3 seconds if no device detected</span></div>
<div class="line">    <span class="keyword">auto</span> devices = <a class="code" href="group__xv__functions.html#ga7a7e38fd3ed94aab311fbc1ce5bd7693">xv::getDevices</a>(5.);</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// if no device: quit</span></div>
<div class="line">    <span class="keywordflow">if</span> (devices.empty()) {</div>
<div class="line">        std::cerr &lt;&lt; <span class="stringliteral">&quot;Timeout for device detection.&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">        <span class="keywordflow">return</span> EXIT_FAILURE;</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// take the first device in the map</span></div>
<div class="line">    <span class="keyword">auto</span> device = devices.begin()-&gt;second;</div>
<div class="line"> </div>
<div class="line">    <span class="keywordflow">if</span> (!device-&gt;slam()) {</div>
<div class="line">        std::cerr &lt;&lt; <span class="stringliteral">&quot;Host SLAM algorithm not supported.&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">        <span class="keywordflow">return</span> EXIT_FAILURE;</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// register a callback to get the current pose based on SLAM, the callback is call at IMU framerate.</span></div>
<div class="line">    <span class="comment">// Framerate can be high, for AR/VR device we recommand using `getPose` function to get the current 6dof pose with no latency.</span></div>
<div class="line">    device-&gt;slam()-&gt;registerPoseCallback(onPose);</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// if access to full stereo camera images it is possible to get images via a callback :</span></div>
<div class="line">    <span class="keywordflow">if</span> (device-&gt;fisheyeCameras()) {</div>
<div class="line">        device-&gt;fisheyeCameras()-&gt;registerCallback([](std::shared_ptr&lt;const xv::FisheyeImages&gt; images) {</div>
<div class="line">            lastStereoImage = images;</div>
<div class="line">            <span class="keyword">static</span> FrequencyCounter fps;</div>
<div class="line">            fps.tic();</div>
<div class="line">            <span class="keywordflow">if</span> (fps.count() % 30 == 1) {</div>
<div class="line">                std::cout &lt;&lt; <span class="stringliteral">&quot;Fisheyes : &quot;</span> &lt;&lt; fps.fps() &lt;&lt; <span class="stringliteral">&quot; Hz&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">            }</div>
<div class="line">        });</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// Simulate a 60Hz loop to show the use of the `getPose` function.</span></div>
<div class="line">    std::atomic&lt;bool&gt; stop(<span class="keyword">false</span>);</div>
<div class="line">    std::thread threadLoop60Hz([&amp;stop, &amp;device]{</div>
<div class="line"> </div>
<div class="line">        <span class="keywordflow">while</span> (!stop) {</div>
<div class="line"> </div>
<div class="line">            <span class="keyword">auto</span> now = std::chrono::steady_clock::now();</div>
<div class="line"> </div>
<div class="line">            <a class="code" href="structxv_1_1Pose.html">xv::Pose</a> pose;</div>
<div class="line">            <span class="comment">// get the pose at current time (no latency because internally compensated with small prediction after the last IMU data received) ...</span></div>
<div class="line">            <span class="keywordflow">if</span> (device-&gt;slam()-&gt;getPose(pose)) {</div>
<div class="line">                <span class="keyword">auto</span> pitchYawRoll = <a class="code" href="group__xv__rotation__conversions.html#ga2e933d4631944d4ab6ff3d0aa0ce7223">xv::rotationToPitchYawRoll</a>(pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#ade74f0f888c9c3727e737114d39689f4">rotation</a>());</div>
<div class="line">                <span class="keyword">static</span> FrequencyCounter fps;</div>
<div class="line">                fps.tic();</div>
<div class="line">                <span class="keywordflow">if</span> (fps.count() % 120 == 1) {</div>
<div class="line">                    std::cout &lt;&lt; <span class="stringliteral">&quot;Current SLAM : &quot;</span> &lt;&lt; fps.fps() &lt;&lt; <span class="stringliteral">&quot; Hz [timestamp=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1PoseRot__.html#a8013d9baf7f36cb63d15070ab1b92db0">hostTimestamp</a>() &lt;&lt; <span class="stringliteral">&quot; x=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a5d341d3f04038517496720505a27d492">x</a>() &lt;&lt; <span class="stringliteral">&quot; y=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a8c459545f7d46d2f237628fce8c05b2f">y</a>() &lt;&lt; <span class="stringliteral">&quot; z=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a28695437773c81547650749af7abd45f">z</a>()</div>
<div class="line">                              &lt;&lt; <span class="stringliteral">&quot; pitch=&quot;</span>  &lt;&lt; pitchYawRoll[0]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; yaw=&quot;</span>  &lt;&lt; pitchYawRoll[1]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; roll=&quot;</span>  &lt;&lt; pitchYawRoll[2]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span></div>
<div class="line">                              &lt;&lt; std::endl;</div>
<div class="line">                }</div>
<div class="line">            }</div>
<div class="line"> </div>
<div class="line">            <span class="comment">// it is also possible to make prediction and to get the pose 30 ms in the future:</span></div>
<div class="line">            <a class="code" href="structxv_1_1Pose.html">xv::Pose</a> pose30ms;</div>
<div class="line">            device-&gt;slam()-&gt;getPose(pose30ms, 0.030);</div>
<div class="line"> </div>
<div class="line">            <span class="keywordflow">if</span> (lastStereoImage) {</div>
<div class="line">                <span class="comment">// it is also possible to get the pose at a given time, for example the last stereo images time:</span></div>
<div class="line">                <a class="code" href="structxv_1_1Pose.html">xv::Pose</a> poseAtStereoImage;</div>
<div class="line">                device-&gt;slam()-&gt;getPoseAt(poseAtStereoImage, lastStereoImage-&gt;<a class="code" href="structxv_1_1FisheyeImages.html#a8f9367a14630d621adabe66e07b7c7df">hostTimestamp</a>);</div>
<div class="line">            }</div>
<div class="line"> </div>
<div class="line">            <span class="comment">// it is also possible to get the pose of the device at a specific timestamp (based on std::chrono::steady_clock)</span></div>
<div class="line">            <span class="comment">// the pose cannot be to old and not too much in the future</span></div>
<div class="line">            <span class="keywordtype">double</span> t = std::chrono::duration_cast&lt;std::chrono::seconds&gt;(std::chrono::steady_clock::now().time_since_epoch()).count();</div>
<div class="line">            t += 0.0123;</div>
<div class="line">            <a class="code" href="structxv_1_1Pose.html">xv::Pose</a> poseAt;</div>
<div class="line">            device-&gt;slam()-&gt;getPoseAt(poseAt, t);</div>
<div class="line"> </div>
<div class="line">            <span class="comment">// to simulate the 60Hz loop</span></div>
<div class="line">            std::this_thread::sleep_until(now+std::chrono::microseconds(<span class="keywordtype">long</span>(1./60.*1e6)));</div>
<div class="line">        }</div>
<div class="line"> </div>
<div class="line">    });</div>
<div class="line"> </div>
<div class="line">    std::cout &lt;&lt; <span class="stringliteral">&quot;Press enter to start SLAM ...&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">    std::cin.get();</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// start the SLAM</span></div>
<div class="line">    device-&gt;slam()-&gt;start();</div>
<div class="line"> </div>
<div class="line">    std::cout &lt;&lt; <span class="stringliteral">&quot;Press enter to stop SLAM ...&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">    std::cin.get();</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// stop the slam</span></div>
<div class="line">    device-&gt;slam()-&gt;stop();</div>
<div class="line"> </div>
<div class="line">    stop = <span class="keyword">true</span>;</div>
<div class="line"> </div>
<div class="line">    <span class="keywordflow">if</span> (threadLoop60Hz.joinable()) {</div>
<div class="line">        threadLoop60Hz.join();</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="keywordflow">return</span> EXIT_SUCCESS;</div>
<div class="line">}</div>
</div><!-- fragment --><h3>Edge SLAM 6dof pose tracking and RGB camera output</h3>
<div class="fragment"><div class="line"><span class="preprocessor">#include &lt;xv-sdk.h&gt;</span></div>
<div class="line"> </div>
<div class="line"><span class="preprocessor">#include &lt;iostream&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;thread&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;atomic&gt;</span></div>
<div class="line"><span class="preprocessor">#include &lt;cmath&gt;</span></div>
<div class="line"> </div>
<div class="line"><span class="preprocessor">#include &quot;frequency_counter.hpp&quot;</span></div>
<div class="line"> </div>
<div class="line"><span class="keywordtype">void</span> onPose(<a class="code" href="structxv_1_1Pose.html">xv::Pose</a> <span class="keyword">const</span>&amp; pose){</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// use the conversion function to get the pitch, yaw and roll of the orientation</span></div>
<div class="line">    <span class="comment">// (be carefull of gimbal lock of Euler angles, that is why Euler angles are not in Pose structure)</span></div>
<div class="line">    <span class="keyword">auto</span> pitchYawRoll = <a class="code" href="group__xv__rotation__conversions.html#ga2e933d4631944d4ab6ff3d0aa0ce7223">xv::rotationToPitchYawRoll</a>(pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#ade74f0f888c9c3727e737114d39689f4">rotation</a>());</div>
<div class="line">    <span class="keyword">static</span> FrequencyCounter fps;</div>
<div class="line">    fps.tic();</div>
<div class="line">    <span class="keywordflow">if</span> (fps.count() % 120 == 1) {</div>
<div class="line">        std::cout &lt;&lt; <span class="stringliteral">&quot;Current SLAM : &quot;</span> &lt;&lt; fps.fps() &lt;&lt; <span class="stringliteral">&quot; Hz [timestamp=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1PoseRot__.html#a8013d9baf7f36cb63d15070ab1b92db0">hostTimestamp</a>() &lt;&lt; <span class="stringliteral">&quot; x=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a5d341d3f04038517496720505a27d492">x</a>() &lt;&lt; <span class="stringliteral">&quot; y=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a8c459545f7d46d2f237628fce8c05b2f">y</a>() &lt;&lt; <span class="stringliteral">&quot; z=&quot;</span> &lt;&lt; pose.<a class="code" href="classxv_1_1details_1_1Transform__.html#a28695437773c81547650749af7abd45f">z</a>()</div>
<div class="line">                  &lt;&lt; <span class="stringliteral">&quot; pitch=&quot;</span>  &lt;&lt; pitchYawRoll[0]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; yaw=&quot;</span>  &lt;&lt; pitchYawRoll[1]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span> &lt;&lt; <span class="stringliteral">&quot; roll=&quot;</span>  &lt;&lt; pitchYawRoll[2]*180./M_PI &lt;&lt; <span class="stringliteral">&quot;°&quot;</span></div>
<div class="line">                  &lt;&lt; std::endl;</div>
<div class="line">    }</div>
<div class="line">}</div>
<div class="line"> </div>
<div class="line">std::shared_ptr&lt;const xv::ColorImage&gt; lastColorImage;</div>
<div class="line"> </div>
<div class="line"><span class="keywordtype">int</span> main( <span class="keywordtype">int</span> <span class="comment">/*argc*/</span>, <span class="keywordtype">char</span>* <span class="comment">/*argv*/</span>[] )</div>
<div class="line">{</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// return a map of devices with serial number as key, wait at most 3 seconds if no device detected</span></div>
<div class="line">    <span class="keyword">auto</span> devices = <a class="code" href="group__xv__functions.html#ga7a7e38fd3ed94aab311fbc1ce5bd7693">xv::getDevices</a>(3.);</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// if no device: quit</span></div>
<div class="line">    <span class="keywordflow">if</span> (devices.empty()) {</div>
<div class="line">        std::cerr &lt;&lt; <span class="stringliteral">&quot;Timeout for device detection.&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">        <span class="keywordflow">return</span> EXIT_FAILURE;</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// take the first device in the map</span></div>
<div class="line">    <span class="keyword">auto</span> device = devices.begin()-&gt;second;</div>
<div class="line"> </div>
<div class="line">    <span class="keywordflow">if</span> (!device-&gt;edge()) {</div>
<div class="line">        std::cerr &lt;&lt; <span class="stringliteral">&quot;Edge SLAM algorithm not supported.&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">        <span class="keywordflow">return</span> EXIT_FAILURE;</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// register a callback to get the current pose based on edge SLAM, the callback is call at IMU framerate.</span></div>
<div class="line">    device-&gt;edge()-&gt;registerPoseCallback(onPose);</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// if access to full stereo camera images it is possible to get images via a callback :</span></div>
<div class="line">    <span class="keywordflow">if</span> (device-&gt;colorCamera()) {</div>
<div class="line">        device-&gt;colorCamera()-&gt;registerCallback([](std::shared_ptr&lt;const xv::ColorImage&gt; image) {</div>
<div class="line">            lastColorImage = image;</div>
<div class="line">            <span class="keyword">static</span> FrequencyCounter fps;</div>
<div class="line">            fps.tic();</div>
<div class="line">            <span class="keywordflow">if</span> (fps.count() % 120 == 1) {</div>
<div class="line">                std::cout &lt;&lt; <span class="stringliteral">&quot;Current color image : &quot;</span> &lt;&lt; fps.fps() &lt;&lt; <span class="stringliteral">&quot; Hz [timestamp=&quot;</span> &lt;&lt; image-&gt;hostTimestamp &lt;&lt; <span class="stringliteral">&quot; width=&quot;</span> &lt;&lt; image-&gt;width &lt;&lt; <span class="stringliteral">&quot; height=&quot;</span> &lt;&lt; image-&gt;height</div>
<div class="line">                          &lt;&lt; <span class="stringliteral">&quot;]&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">            }</div>
<div class="line">        });</div>
<div class="line">    } <span class="keywordflow">else</span> {</div>
<div class="line">        std::cerr &lt;&lt; <span class="stringliteral">&quot;Access to color camera not supported.&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">        <span class="keywordflow">return</span> EXIT_FAILURE;</div>
<div class="line">    }</div>
<div class="line"> </div>
<div class="line">    std::cout &lt;&lt; <span class="stringliteral">&quot;Press enter to start SLAM ...&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">    std::cin.get();</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// start the SLAM</span></div>
<div class="line">    device-&gt;edge()-&gt;start();</div>
<div class="line"> </div>
<div class="line">    std::cout &lt;&lt; <span class="stringliteral">&quot;Press enter to stop SLAM ...&quot;</span> &lt;&lt; std::endl;</div>
<div class="line">    std::cin.get();</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// to get the a color image in RGB format, can do the conversion with:</span></div>
<div class="line">    <a class="code" href="structxv_1_1RgbImage.html">xv::RgbImage</a> rgbImage = lastColorImage-&gt;<a class="code" href="structxv_1_1ColorImage.html#ac121c766dfffb02b589b5cd36ad2deba">toRgb</a>();</div>
<div class="line"> </div>
<div class="line">    <span class="comment">// stop the slam</span></div>
<div class="line">    device-&gt;edge()-&gt;stop();</div>
<div class="line"> </div>
<div class="line">    <span class="keywordflow">return</span> EXIT_SUCCESS;</div>
<div class="line">}</div>
</div><!-- fragment --> </div></div><!-- PageDoc -->
</div><!-- contents -->
<div class="ttc" id="aclassxv_1_1details_1_1Transform___html_a8c459545f7d46d2f237628fce8c05b2f"><div class="ttname"><a href="classxv_1_1details_1_1Transform__.html#a8c459545f7d46d2f237628fce8c05b2f">xv::details::Transform_::y</a></div><div class="ttdeci">F y() const</div><div class="ttdoc">Y coordinate of the translation.</div><div class="ttdef"><b>Definition:</b> xv-types.h:292</div></div>
<div class="ttc" id="agroup__xv__functions_html_ga32fe1b6690843af286b55a88691c10fa"><div class="ttname"><a href="group__xv__functions.html#ga32fe1b6690843af286b55a88691c10fa">xv::setLogLevel</a></div><div class="ttdeci">void setLogLevel(LogLevel l)</div><div class="ttdoc">Change the log level.</div></div>
<div class="ttc" id="aclassxv_1_1details_1_1Transform___html_a5d341d3f04038517496720505a27d492"><div class="ttname"><a href="classxv_1_1details_1_1Transform__.html#a5d341d3f04038517496720505a27d492">xv::details::Transform_::x</a></div><div class="ttdeci">F x() const</div><div class="ttdoc">X coordinate of the translation.</div><div class="ttdef"><b>Definition:</b> xv-types.h:288</div></div>
<div class="ttc" id="astructxv_1_1RgbImage_html"><div class="ttname"><a href="structxv_1_1RgbImage.html">xv::RgbImage</a></div><div class="ttdoc">A color image in RGB format.</div><div class="ttdef"><b>Definition:</b> xv-types.h:1037</div></div>
<div class="ttc" id="astructxv_1_1Pose_html"><div class="ttname"><a href="structxv_1_1Pose.html">xv::Pose</a></div><div class="ttdoc">Class representing a 6dof pose at a timestamp with a linear model for prediction.</div><div class="ttdef"><b>Definition:</b> xv-types.h:796</div></div>
<div class="ttc" id="agroup__xv__rotation__conversions_html_ga2e933d4631944d4ab6ff3d0aa0ce7223"><div class="ttname"><a href="group__xv__rotation__conversions.html#ga2e933d4631944d4ab6ff3d0aa0ce7223">xv::rotationToPitchYawRoll</a></div><div class="ttdeci">Vector3d rotationToPitchYawRoll(Matrix3d const &amp;rot)</div><div class="ttdoc">Convert rotation Euler angles.</div></div>
<div class="ttc" id="aclassxv_1_1details_1_1Transform___html_ade74f0f888c9c3727e737114d39689f4"><div class="ttname"><a href="classxv_1_1details_1_1Transform__.html#ade74f0f888c9c3727e737114d39689f4">xv::details::Transform_::rotation</a></div><div class="ttdeci">Matrix3&lt; F &gt; const  &amp; rotation() const</div><div class="ttdoc">Get the rotation matrix part of the transformation.</div><div class="ttdef"><b>Definition:</b> xv-types.h:275</div></div>
<div class="ttc" id="aclassxv_1_1details_1_1Transform___html_a28695437773c81547650749af7abd45f"><div class="ttname"><a href="classxv_1_1details_1_1Transform__.html#a28695437773c81547650749af7abd45f">xv::details::Transform_::z</a></div><div class="ttdeci">F z() const</div><div class="ttdoc">Z coordinate of the translation.</div><div class="ttdef"><b>Definition:</b> xv-types.h:296</div></div>
<div class="ttc" id="aclassxv_1_1details_1_1PoseRot___html_a8013d9baf7f36cb63d15070ab1b92db0"><div class="ttname"><a href="classxv_1_1details_1_1PoseRot__.html#a8013d9baf7f36cb63d15070ab1b92db0">xv::details::PoseRot_::hostTimestamp</a></div><div class="ttdeci">double hostTimestamp() const</div><div class="ttdoc">Get the host timestamp of the pose (in s).</div><div class="ttdef"><b>Definition:</b> xv-types.h:458</div></div>
<div class="ttc" id="astructxv_1_1FisheyeImages_html_a8f9367a14630d621adabe66e07b7c7df"><div class="ttname"><a href="structxv_1_1FisheyeImages.html#a8f9367a14630d621adabe66e07b7c7df">xv::FisheyeImages::hostTimestamp</a></div><div class="ttdeci">double hostTimestamp</div><div class="ttdoc">host timestamp of the physical measurement (in second based on the std::chrono::steady_clock),...</div><div class="ttdef"><b>Definition:</b> xv-types.h:1028</div></div>
<div class="ttc" id="agroup__xv__functions_html_ga7a7e38fd3ed94aab311fbc1ce5bd7693"><div class="ttname"><a href="group__xv__functions.html#ga7a7e38fd3ed94aab311fbc1ce5bd7693">xv::getDevices</a></div><div class="ttdeci">std::map&lt; std::string, std::shared_ptr&lt; Device &gt; &gt; getDevices(double timeOut=0., const std::string &amp;desc=&quot;&quot;, bool *stopWaiting=nullptr, xv::SlamStartMode slamStartMode=xv::SlamStartMode::Normal, xv::DeviceSupport deviceSupport=xv::DeviceSupport ::ONLYUSB)</div><div class="ttdoc">Retrieve all the detected XVisio devices. If no device is found after the timeout is reached,...</div></div>
<div class="ttc" id="astructxv_1_1ColorImage_html_ac121c766dfffb02b589b5cd36ad2deba"><div class="ttname"><a href="structxv_1_1ColorImage.html#ac121c766dfffb02b589b5cd36ad2deba">xv::ColorImage::toRgb</a></div><div class="ttdeci">RgbImage toRgb() const</div><div class="ttdoc">Convert to a xv::RgbImage.</div></div>
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.17
</small></address>
</body>
</html>
